admin_ad_videoblock_index:
  path: /
  methods: [GET]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::indexAction'
    _legacy_controller: 'AdminVideoBlock'
    _legacy_link: 'AdminVideoBlock'

admin_ad_videoblock_search:
    path: /
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Common:searchGrid
        gridDefinitionFactoryServiceId: advideoblock.grid.factory.videoblock_grid_definition_factory
        redirectRoute: admin_ad_videoblock_index
        _legacy_controller: 'AdminVideoBlock'
        _legacy_link: 'AdminVideoBlock:search'

admin_ad_videoblock_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::createAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_edit:
  path: /{id}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::editAction'
    _legacy_controller: 'AdminVideoBlock'
  requirements:
    id: \d+

admin_ad_videoblock_delete:
  path: /delete
  methods: [DELETE]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::deleteAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_delete_bulk:
  path: /delete-bulk
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::deleteBulkAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_enable_bulk:
  path: /enable-bulk
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::enableBulkAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_disable_bulk:
  path: /disable-bulk
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::disableBulkAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_duplicate_bulk:
    path: /duplicate-bulk
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::duplicateBulkAction'
        _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_toggle_fullscreen:
    path: /{id}/toggle-fullscreen
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::toggleFullscreenAction'
        _legacy_controller: 'AdminVideoBlock'
    requirements:
        id: \d+

admin_ad_videoblock_toggle_status:
    path: /{id}/toggle-status
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::toggleStatusAction'
        _legacy_controller: 'AdminVideoBlock'
    requirements:
        id: \d+
