admin_ad_videoblock_index:
  path: /
  methods: [GET]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::indexAction'
    _legacy_controller: 'AdminVideoBlock'
    _legacy_link: 'AdminVideoBlock'

admin_ad_videoblock_search:
  path: /
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::searchAction'
    _legacy_controller: 'AdminVideoBlock'
    _legacy_link: 'AdminVideoBlock:search'

admin_ad_videoblock_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::createAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_edit:
  path: /{id}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::editAction'
    _legacy_controller: 'AdminVideoBlock'
  requirements:
    id: \d+

admin_ad_videoblock_delete:
  path: /{id}/delete
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::deleteAction'
    _legacy_controller: 'AdminVideoBlock'
  requirements:
    id: \d+

admin_ad_videoblock_delete_bulk:
  path: /delete-bulk
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::deleteBulkAction'
    _legacy_controller: 'AdminVideoBlock'


admin_ad_videoblock_toggle_fullscreen:
    path: /{id}/toggle-fullscreen
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::toggleFullscreenAction'
        _legacy_controller: 'AdminVideoBlock'
    requirements:
        id: \d+

admin_ad_videoblock_toggle_status:
    path: /{id}/toggle-status
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\Ad_VideoBlockController::toggleStatusAction'
        _legacy_controller: 'AdminVideoBlock'
    requirements:
        id: \d+
