admin_ad_videoblock_index:
  path: /videoblock/
  methods: [GET]
  defaults:
    _controller: 'AdVideoBlock\Controller\VideoBlockController::indexAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_search:
    path: /videoblock/
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Common:searchGrid
        gridDefinitionFactoryServiceId: advideoblock.grid.factory.definition.videoblock
        redirectRoute: admin_ad_videoblock_index
        _legacy_controller: 'AdminVideoBlock'
        _legacy_link: 'AdminVideoBlock:submitFiltervideoblock'

admin_ad_videoblock_create:
  path: /videoblock/new
  methods: [GET, POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\VideoBlockController::createAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_edit:
  path: /videoblock/{id}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\VideoBlockController::editAction'
    _legacy_controller: 'AdminVideoBlock'
  requirements:
    id: \d+

admin_ad_videoblock_delete:
  path: /videoblock/delete
  methods: [DELETE]
  defaults:
    _controller: 'AdVideoBlock\Controller\VideoBlockController::deleteAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_toggle_fullscreen:
    path: /videoblock/{id}/toggle-fullscreen
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\VideoBlockController::toggleFullscreenAction'
        _legacy_controller: 'AdminVideoBlock'
    requirements:
        id: \d+

admin_ad_videoblock_toggle_active:
    path: /videoblock/{id}/toggle-active
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\VideoBlockController::toggleActiveAction'
        _legacy_controller: 'AdminVideoBlock'
    requirements:
        id: \d+

admin_ad_videoblock_duplicate_bulk:
    path: /videoblock/duplicate-bulk
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\VideoBlockController::duplicateBulkAction'
        _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_active_bulk:
  path: /videoblock/active-bulk
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\VideoBlockController::activeBulkAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_fullscreen_bulk:
  path: /videoblock/fullscreen-bulk
  methods: [POST]
  defaults:
    _controller: 'AdVideoBlock\Controller\VideoBlockController::fullscreenBulkAction'
    _legacy_controller: 'AdminVideoBlock'

admin_ad_videoblock_delete_bulk:
    path: /videoblock/delete-bulk
    methods: [POST]
    defaults:
        _controller: 'AdVideoBlock\Controller\VideoBlockController::deleteBulkAction'
        _legacy_controller: 'AdminVideoBlock'

